# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4466fc05f9f4f84f40b5cca3ca3cd72752933d2751747b9a5e5e6e58d32b11e69c70e03c4971a0a5abd3144ec2763bd3924914a3f47d04ffc4293fd27a1bd662

test:
  secret_key_base: 0177080458653cca72a8dd9e0b88d0770ad8162cdfe29c7e80564cdae91fdb6cea2c2910b33a68e75df73608a853168b8916179f540b888800cbb32919f36534

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
